# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip-notes" do
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_macos do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v1.1.1/snip_Darwin_x86_64.tar.gz"
      sha256 "3f750a72618e284eda0129c2993b67c8b16457ffabb5dd576d6f4f8205666689"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v1.1.1/snip_Darwin_arm64.tar.gz"
      sha256 "38a97acf8a606291e0cf63bf1564a7ed4948d7850f2354ba9c07b15cd21f49a7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snip"]
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
