# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip-notes" do
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_macos do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v0.3.0/snip_Darwin_x86_64.tar.gz"
      sha256 "fb4e7214e1fcc13bf8f73817f40da580b814bc58ea9fc3614dba87c16f12fdc8"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v0.3.0/snip_Darwin_arm64.tar.gz"
      sha256 "ae7cd29dab313bf239d4ca749db7a6c00d2fd1c629f6610f43c48259ec6b0825"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snip"]
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
