# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip" do
  name "snip"
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_linux do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_x86_64.tar.gz"
      sha256 "4b333ebb8d57d5fd81b982fcd7694216f99ae4f33980b7d684b1384b3ee81f66"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_arm64.tar.gz"
      sha256 "4b1e5bf2654a123817cb0747024d68eca714b569f21c36995ff17f2eef8efd43"
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
