# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip-notes" do
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_macos do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v1.0.0/snip_Darwin_x86_64.tar.gz"
      sha256 "9ad913d49cc99dc4abb799761375db1ea6290c3725449908993680bac2e587c1"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v1.0.0/snip_Darwin_arm64.tar.gz"
      sha256 "5beaa7bd93f0445558a7b8f3d3a7ce191170f45dd23d46c571d3cf365a89607c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snip"]
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
